### ISSUE TITLE
Dependency MigraDocCore.Rendering

### ISSUE THREAD

**Issue by lucdhaenen** [ststeiger/PdfSharpCore#147]
There is a dependency on PDFSharpCore.Charting >= 0.1.1
Version on Nuget = 0.1.0
I'm not able to install the complete package....Any advise please?

**Comment by startnow65** [comment]
Hi @lucdhaenen 

Sorry, I just realized that `MigraDocCore.Rendering` still references `PdfSharpCore.Charting` via direct project reference instead of via the nugget and thereby causing the version lockstep.

I just published version `0.1.1` of `PdfSharpCore.Charting` to unblock you. Would fix the dependency issue shortly

**Comment by lucdhaenen** [comment]
Works like a charm now.....Thks :)
