### ISSUE TITLE
Project "CoreDb" is missing

### ISSUE THREAD

**Issue by jogibear9988** [ststeiger/PdfSharpCore#15]
The Project CoreDb is missing in the Repo

**Comment by ststeiger** [comment]
[Project CoreDb is in the repositories here](https://github.com/ststeiger/CoreDAL/tree/master/CoreDb).
It was just used to read the data from the SQL database. 

I think if I remember right I experimented with git submodules, so if you'd do a git submodule init, git would fetch it  - i think. It didn't work well because VS does not really support submodules.

**Comment by jogibear9988** [comment]
Maybe it would be a good Idea, to remove Stammbaum and CoreDB from the Repo and the Solution, and maintain only this in the Repo?
And create a new Repo "Stammbaum" wich refernces the PdfSharpCore nugets and has the "CoreDB" submodule inside?

**Comment by ststeiger** [comment]
Agreed, will do that on the weekend.

**Comment by ststeiger** [comment]
Finally, found time to do that. 
Moved entire example to different project.
