### ISSUE TITLE
Add security password to PDF

### ISSUE THREAD

**Issue by sanglanun** [ststeiger/PdfSharpCore#17]
Hi, I'm follow this [sample](http://www.pdfsharp.net/wiki/ProtectDocument-sample.ashx) to add password security into the PDF generated. But there is an error here.
![1](https://user-images.githubusercontent.com/6336820/44842973-c622f480-ac79-11e8-9401-4635268c1054.PNG)

Below is my code for adding security:
`PdfSecuritySettings securitySettings = document.SecuritySettings;`
`securitySettings.UserPassword = "user";`
`securitySettings.OwnerPassword = "owner";`

I already checking PDFSharp forum, but didn't found any error regarding this. Can you help me?

**Comment by ststeiger** [comment]
@anglanun: Fixed missing MD5-implementation with [commit 783079e2023732a6f6068e450d589dfeec863c70](https://github.com/ststeiger/PdfSharpCore/commit/783079e2023732a6f6068e450d589dfeec863c70)

Fixed with [with mono implementation of TransformBlock and TransformFinalBlock](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/security/cryptography/hashalgorithm.cs). 
UserPassword & OwnerPassword now works ! 

@startnow65: Could you update the nuget ?

**Comment by startnow65** [comment]
Updated.
Almost done with the CI part that pushes a new nugget upon merge to master

**Comment by ststeiger** [comment]
Great news. 
@sanglanun: Pull the latest version from nuget. 
It's fixed. 
I'm closing the issue now.

**Comment by sanglanun** [comment]
Thanks guys. It works now. Awesome 👍
