### ISSUE TITLE
XImage.FromStream fails because of missing ImageSource.ImageSourceImpl

### ISSUE THREAD

**Issue by TimSharK** [ststeiger/PdfSharpCore#18]
```
var assembly = Assembly.GetEntryAssembly();
var stream = assembly.GetManifestResourceStream("Project.Resource.image.png");
var img = XImage.FromStream(() => stream);
```

It throws NRE

I want to use this image in XGraphics.DrawImage function

**Comment by ststeiger** [comment]
DrawImage works. 
If you looked at the sample, you see that you need to set the ImageSourceImpl at program startup. 
Did you do that ? 

```
MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes
                .ImageSource.ImageSourceImpl = new PdfSharpCore.ImageSharp.ImageSharpImageSource<Rgba32>();
```

**Comment by TimSharK** [comment]
But nuget package doesn't contain PdfSharpCore.ImageSharp project...
I've checked it via Object Browser

**Comment by startnow65** [comment]
Hi @TimSharK, yes the nugget package does not contain the PdfSharpCore.ImageSharp project.

The Library allows you to implement an Image Source to suit you. For my project, i just use the implementation in the PdfSharpCore.ImageSharp by just copying the class directly.

You also need to implement a FontResolver. The font resolver I implemented for my project for example, is a bit different from what was implemented in the Stammbaum project. The one in the project may just work for you.

@ststeiger Would it be a good idea to bring in these two classes (ImageSharpImageSource and FontResolver) into PdfSharpCore as default implementations so we have a complete library. User can of course override them or have a different implementation entirely. If its fine by you, I can make a PR for it.
It does not make a lot of sense building another Nugget on the PdfSharpCore.ImageSharp since it has only one Class.

**Comment by arbrown** [comment]
I think it makes sense to include the ImageSharpImageSource class in the NuGet package.  I was really confused why it showed up in the repository but not the NuGet package until I downloaded and built the solution from source.  Is there a reason this was omitted in the first place?
