### ISSUE TITLE
 Japanese, Chinese characters are not rendered in Xamarin (Android 11)

### ISSUE THREAD

**Issue by mikekrueger81** [ststeiger/PdfSharpCore#188]
PdfSharpCore Version 1.3.7

This is my Xamarin Android App
![image](https://user-images.githubusercontent.com/73218090/135281330-36179aa0-bf28-4864-a31b-2f9abe571d3f.png)

This is the rendered PDF
![image](https://user-images.githubusercontent.com/73218090/135281622-a1038ec0-f4c5-4866-a9f0-72263786c3e5.png)

**Comment by ststeiger** [comment]
Have you use a Chinese-capable font , such as google-noto-cjk ?

**Comment by mikekrueger81** [comment]
At the moment I am playing around with this font.
[Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP)

## But I have some strange effects:

* My PDF file is over 3 megabytes in size (with NotoSans-Regular the file was only about 100 kilobytes )
* The PDF looks good on Android but on Windows the encoding seems to be wrong.

## Android PDF Viewer
![image](https://user-images.githubusercontent.com/73218090/135422823-a92aa656-b209-4d6d-a32b-9bf262ac01ab.png)

## opened the same PDF with a **Windows PDF viewer**
![image](https://user-images.githubusercontent.com/73218090/135423130-9116cb63-44d7-46bb-9473-83cdccfc4dc0.png)

here is the sample PDF:
[SinglePage (18).pdf](https://github.com/ststeiger/PdfSharpCore/files/7258259/SinglePage.18.pdf)

**Comment by ststeiger** [comment]
The font-file gets embedded in the PDF wholesale on Linux (Android). 
(there's no CreateFontPackage Windows-API-call on Linux)
The most-likely reason is "NotoSans-Regular"-TrueType-file is much smaller than the "Noto Sans Japanese"-OpenType-file. 

The reason it doesn't look correct on Windows might be that Noto Japanese is not installed. 
That might mean embedding OpenType-files does not work because it expects a truetype-font. 

Maybe you could try convert the OpenType-file to TrueType (assuming TrueType supports that - there is probably a reason why they chose OpenType for Asian fonts): 
https://convertio.co/otf-ttf/

Also, be sure to check what happens if you copy the noto-font-file to C:\Windows\Fonts on Windows. 
If it should display correctly afterwards, it's definitely a font-embedding issue.

**Comment by mikekrueger81** [comment]
[I found your .Net runtime bug report](https://github.com/dotnet/runtime/issues/49065).
This means that there is currently no way to create PDF files with Asian characters on Android/Linux/iOS . ?! :(
Installing the font on the operating system on which you want to read the PDF does not make sense either. I thought the P in PDF stands for Portable :D

But Thank you for your Support! 
You have done a good job with this library.
