### ISSUE TITLE
NullReferenceException with ImageSource.FromStream

### ISSUE THREAD

**Issue by colejohnson66** [ststeiger/PdfSharpCore#196]
I am getting a `NullReferenceException` when I call `ImageSource.FromStream`. The problem appears to be that `ImageSource.ImageSourceImpl` is `null`. The only place I can find where this variable is set are in `XImage`, which I am not using.

**Comment by Bogdancev** [comment]
That is how I'm doing it:

```
protected ImageSource.IImageSource GetEmbeddedImage(string Name, string Path)
{
    Assembly assembly = Assembly.GetExecutingAssembly();
    if (ImageSource.ImageSourceImpl == null)
        ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();

    return ImageSource.FromStream(Name, () => assembly.GetManifestResourceStream(Path));
}
```

**Comment by colejohnson66** [comment]
Yep. I ended up having to initialize it myself like you did. But the bug is that this null check should be in PdfSharpCore, not my code.

**Comment by ststeiger** [comment]
@colejohnson66: 
No, the bug is that you did not initialize the image source in PdfSharpCore on initialization of PdfSharpCore. 
However, doing 
```
if (ImageSource.ImageSourceImpl == null)
        ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();
```
might end you up in a race-condition in a multi-threaded environment. 
So you really should initialize it on program startup.

**Comment by colejohnson66** [comment]
If I am expected to do this, why is it not documented, and why does XImage do it then?

**Comment by ststeiger** [comment]
It's not documented anywhere, you just have to notice it yourselfs ;)
It's a quirk from the original author, which is not me. 

> why does XImage do it then

Good point. 
That probably shouldn't be. 
But if I change that now, I risk breaking other people's stuff...

I'm going to document it,  should I ever find the time to do so. <br />
In the meantime, I'm happy to accept pull-requests. 

I had the same problem originally.<br />
Took me some 5 minutes to figure it out.<br />
You can see it [here](https://github.com/ststeiger/Stammbaum/blob/master/Stammbaum/Program.cs).
`MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource.ImageSourceImpl = new PdfSharpCore.ImageSharp.ImageSharpImageSource<SixLabors.ImageSharp.PixelFormats.Rgba32>();`

I originally ported PdfSharp to .NET Core because I wanted to print a family tree (Stammbaum in German). <br />
Found some old stuff which used .NET Core 1.1 and ported it to 2.0. The result is this repository. 
But a pedigree tree is not quite that simple as an ever-expanding power-of-two-orgchart. One actually needs to do a far more sophisticated graph, so I went [with d3](https://stackoverflow.com/questions/11137238/d3js-tree-square) instead. I'm doing the PDF with Chrome-Dev-Tools now.
