### ISSUE TITLE
PDF to Image (getting a thumbnail)

### ISSUE THREAD

**Issue by Rbn3D** [ststeiger/PdfSharpCore#27]
Hi!

I know that thumbnail support is not even part of PDFSharp, but, it is feasible to implement it on PDFSharpCore? Would be very useful to get a thumbnail of a given PDFPage.

Not sure how complex this can be, but I think there's no need for a production ready PDF-to-image renderer (just small resolution thumbnails).
I don't want to rely on ghostscript or other native libraries, this should be really cross-platform!

Throughts?

Thank you!

**Comment by ststeiger** [comment]
There is something like this in PagePreview in the full version:
https://github.com/ststeiger/PdfSharpNetStandard/blob/master/PdfSharp_Removed/Forms/PagePreview.cs
though I don't know how good it is. 
For .NET Core/NetStandard, it had to be removed, because there is no WPF/WinForms support. 

But really, ghostscript is your best option 
```
gs -q -dQUIET -dPARANOIDSAFER -dBATCH -dNOPAUSE -dNOPROMPT \
-dMaxBitmap=500000000 -dLastPage=1 -dAlignToPixels=0 -dGridFitTT=0 \
-sDEVICE=jpeg -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r72x72 \
-sOutputFile=$OUTPUT -f$INPUT
```

you can use the portable version, then you don't need to install it.

**Comment by Rbn3D** [comment]
@ststeiger Thank you for the quick answer, I'm finally using ghostscript in their portable version, not sure however about the stdout thing, so using files for now.
