### ISSUE TITLE
Conversion from HTML to PDF

### ISSUE THREAD

**Issue by Kameshwaran** [ststeiger/PdfSharpCore#4]
I want to convert html to pdf. How to acheive it with this library. 
```PdfGenerator``` class from ```PdfSharp``` seems to be missing.

**Comment by ststeiger** [comment]
PdfGenerator is part of TheArtOfDev.HtmlRenderer. 
It is not part of PdfSharp itselfs. 
If you need a HTML-to-PDF converter, you can use wkHtmlToPdf. 
Besides, HtmlRenderer is really bad, and I wouldn't use it anyway if I were you. 

If you need a .NET-Core library, I have something in the works here:
https://github.com/ststeiger/libWkHtml2X/blob/master/wkHtmlToXCore/Program.cs 
It's not finished though, so you might have to put in a little work yourselfs. 
So far, I have only added the Windows-binaries, so if you run it on Mac or Linux, you either need to install wkHtmlToPdf globally, or you need to add the respective binaries. 

Keep in mind wkHtmlToPdf is not thread-safe, so it must be run on a single-thread, because QT-WebKit isn't thread-safe. Also, it looks like you need to re-init the converter if you need to convert more than one document in a row.
