### ISSUE TITLE
Create table 

### ISSUE THREAD

**Issue by livioco** [ststeiger/PdfSharpCore#74]
I will try to use PdfSharp with NetCore 3.1. 
There is a method to create easy a table?
The function of migradoc are not included in these version for netcore?

Thanks

**Comment by ststeiger** [comment]
The namespace is MigraDocCore.
Don't know what's in there, never used. 

The easiest way to create a table PDF is to create a html file and print-to-pdf with ChromeDevTools.
https://github.com/MasterDevs/ChromeDevTools

**Comment by livioco** [comment]
Thanks.

In migradoc there is a Table class, but in MigraDocCore i see only shape
MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes

**Comment by Bogdancev** [comment]
Hi Stefan

Is the package **PdfSharpCore** (current version 1.1.25) from NuGet produced by you?

Maybe I'm doing something wrong, but observed behavior is following:
-- If I just install **PdfSharpCore** package, I do not see Tables, Chats, etc in  **MigraDocCore.DocumentObjectModel** namespace and thus I cannot reproduce any MigraDoc [examples](http://pdfsharp.net/wiki/HelloMigraDoc-sample.ashx).
-- If I download your project from GitHub, build it and than in addition to already installed **PdfSharpCore** package add following references to **MigraDocCore.DocumentObjectModel.dll** and **MigraDocCore.Rendering.dll** from my test project, I can reproduce MigraDoc examples, everything works fine.

So if this is your package, were those not included because you were not interested in MicraDoc part? Or maybe I just don't understand how package creation works.

P.S. My dotnet is **.net core 2.1**

Regards, Sergiy

**Comment by startnow65** [comment]
Hi @Bogdancev 

The [PdfSharpCore](https://www.nuget.org/packages/pdfsharpcore/) nugget package is built from this repo and as you pointed out, it does not include the Migradoc part.

It is built from the [PdfSharpCore](https://github.com/ststeiger/PdfSharpCore/tree/master/PdfSharpCore) project in this solution.

**Comment by Bogdancev** [comment]
Hi **@startnow65** 

Can it be included or published separately or this does not make any sense?

**Comment by ststeiger** [comment]
> Hi @Bogdancev
> 
> The [PdfSharpCore](https://www.nuget.org/packages/pdfsharpcore/) nugget package is built from this repo and as you pointed out, it does not include the Migradoc part.
> 
> It is built from the [PdfSharpCore](https://github.com/ststeiger/PdfSharpCore/tree/master/PdfSharpCore) project in this solution.

Ah, now I understand the problem of the people saying they see no migradoc namespace...

**Comment by startnow65** [comment]
Hi @Bogdancev 
I think it would be better to publish it separately.
I see a couple of migradoc nugget packages though.
I can package the migradoc here if the existing ones do not work for you.

@ststeiger Please let me know what you think

**Comment by Bogdancev** [comment]
What I can find so far:

- **MigraDoc.Rendering.Standard** -- depends on Didstopia.PdfSharp and on MigraDoc.DocumentObjectModel.Standard
- **MigraDoc.Rendering.Core** -- this has nothing to do with .net core, and "core" here means something else
- **com.pdfsharpcore.migradoccore.rendering** -- this one looks similar to yours, probably a branch, but it has several dependencies on its own flavors of "com.pdfsharpcore......."

That's all I see regarding to "rendering" part. Other packages with suffix ".standard" have dependency on System.Drawing.Common and I'm not sure how this relates to ImageSharp.

So it looks like whoever has similar package has already supplied separately their own **...DocumentObjectModel...** and **...Rendering...** (plus others) parts

**Comment by ststeiger** [comment]
Yea, all the existing ones won't work, because they are for PdfSharp, not PdfSharpCore. 

> @ststeiger Please let me know what you think
Well, while it's "my" code, it's your package, so you decide what you put in to it and what not. 

When I include MigraDoc in the PdfSharpCore dll, then it's troublesome when I'm gonna remove ImageSharp and replace it with SkiaSharp. In fact, any changes would be troublesome, then. 
So I would rather keep them in their separate package. 
Maybe if you create nother nuget package, add the link in the description. 

Or maybe create a nuget package with several dlls ? 
https://stackoverflow.com/questions/7486651/create-nuget-package-with-multiple-dlls

@Bogdancev: Why don't you just add the PdfSharpCore source for now ? 
Then you don't need to wait for the package. 

MigraDoc in PdfSharpCore is all in the namespace MigraDocCore, btw.

**Comment by ststeiger** [comment]
> Hi @startnow65

> That's all I see regarding to "rendering" part. Other packages with suffix ".standard" have dependency on System.Drawing.Common and I'm not sure how this relates to ImageSharp.

That's imageSharp compiled for NetStandard. 
System.Drawing has been ported to .NET Core meanwhile. 
In its absence prior to .NET Core 2.0, it had to be replaced with ImageSharp. 

System.Drawing is still troublesome, as it won't work correctly on Azure. 
Because you shouldn't use it, because it has memory-leaks. 
(System.Drawing uses GDI+, which was created for a single-user desktop system, not servers - it should not be uses on servers, and by dependence, neither should System.Drawing)

Problem is ImageSharp is an unstable project, breaking backwards-compatibility all the time. 
Plus now they want to change license from Apache2 to a AGPL/Commercial racket.

**Comment by Bogdancev** [comment]
OK, so I created a folder PdfSharpCore in my solution, added all 5 projects there, added README.txt to not forget why all of that. Removed all mentions of netstandard 1.3 and removed package generation settings to not pollute the build process. Also added references to all these projects from my project.

And I now can totally reproduce that complex example from MigraDoc web-site.
I uploaded published files to the hosting and it worked there too.

So far so good.
Thanx

Will there be any notification about new packages or about update of the current package should you decide to make it?

**Comment by startnow65** [comment]
@Bogdancev Yes, would post a comment to this issue

**Comment by ststeiger** [comment]
> OK, so I created a folder PdfSharpCore in my solution, added all 5 projects there, added README.txt to not forget why all of that. 

I think you could also just have added the binaries to a project folder, and add it as reference, like back in the days before nuget, that would have reduced compile-time. 

But if that is fast enough, that's also good, if not better.

**Comment by startnow65** [comment]
https://github.com/ststeiger/PdfSharpCore/pull/83

**Comment by startnow65** [comment]
https://www.nuget.org/packages/PdfSharpCore.Charting/
https://www.nuget.org/packages/MigraDocCore.DocumentObjectModel/
https://www.nuget.org/packages/MigraDocCore.Rendering/

**Comment by ststeiger** [comment]
Nicely done  :thumbsup:

**Comment by Bogdancev** [comment]
Hi

Just finished pdfs in my project, removed PDFSharpCore project files and included NuGet packages instead. Everything works great, thanx!

When project is published, there is **"de"** folder with published files. Is this necessary or is it possible to not publish it as I assume it is some kind of language resource?

Regards, Sergiy
