### ISSUE TITLE
Pages is empty and PageCount is 0 with scanned document

### ISSUE THREAD

**Issue by arturosevilla** [ststeiger/PdfSharpCore#81]
The library does not load any pages with the attached document when loading for importing:

```
using (PdfDocument document = PdfReader.Open(fileContent, PdfDocumentOpenMode.Import))
{
    foreach (PdfPage page in document.Pages)
    {
        _generatedDocument.AddPage(page);
    }
}
```

[1.pdf](https://github.com/ststeiger/PdfSharpCore/files/4555839/1.pdf)

**Comment by LukaszBrzezinski** [comment]
@arturosevilla I'm facing same issue. 

I investigated it and it seems to be xref table problem. 
Regarding attached pdf xref table starts from 1 instead of 0.

xref
1 7
0000000000 65535 f 
0000000009 00000 n 
0000349874 00000 n 
0000349971 00000 n 
0000350158 00000 n 
0000350216 00000 n 
0000350267 00000 n

According to pdf spec:
"Each cross-reference section shall begin with a line containing the keyword xref. Following this line shall be one or more cross-reference subsections, which may appear in any order. For a file that has never been incrementally updated, the cross-reference section shall contain only one subsection, whose object numbering begins at 0."

(7.5.4 Cross-Reference Table) => https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

As a workaround I found that opening pdf in Adobe Acrobat Reader and then saving it again seems to fix issue with xref table. 
I tried also fixing xref table manually and it seems to work too.

But maybe there is a possibility to fix it in PdfSharCore?

**Comment by PoisnFang** [comment]
+1 for this issue

**Comment by PoisnFang** [comment]
@LukaszBrzezinski Is there a work around in the code that I can do?

**Comment by ststeiger** [comment]
@PoisnFang: Thank you very much. 
Merged.
